server :
  port : 12031

spring :
  profiles :
  address : dev
  port : 12030

spring :
  profiles : dev
    active : dev
    include: console-logging, file-logging

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    initialize: true,
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/Meeting4u?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: meeting4u!

  jwt:
    secret: JwtToken

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
    generate-ddl: true
    database: mysql
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  logging:
    level:
      org.springframework: INFO
      org.springframework.web: DEBUG
