server :
  port : 12035

spring :
  profiles :
    include: console-logging, file-logging

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    drive-class-name: org.h2.Driver
    initialize: true,
    initialization-mode: always
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jwt:
    secret: JwtToken

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
    generate-ddl: true
    database: mysql
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  logging:
    level:
      org.springframework: INFO
      org.springframework.web: DEBUG