server :
<<<<<<< HEAD
  port : 12035

spring :
  profiles :
=======
  address : localhost
  port : 12030

spring :
  profiles :
    active : local
>>>>>>> origin/exp/ryunha
    include: console-logging, file-logging

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
<<<<<<< HEAD
    drive-class-name: org.h2.Driver
    initialize: true,
    initialization-mode: always
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
=======
    drive-class-name: com.mysql.cj.jdbc.Driver
    initialize: true,
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/Meeting4u?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: kimrh0609!
>>>>>>> origin/exp/ryunha

  jwt:
    secret: JwtToken

  jpa:
<<<<<<< HEAD
    database-platform: org.hibernate.dialect.H2Dialect
=======
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
>>>>>>> origin/exp/ryunha
    hibernate.ddl-auto: validate
    generate-ddl: true
    database: mysql
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  logging:
    level:
      org.springframework: INFO
      org.springframework.web: DEBUG